name: Terraform AWS Security Group

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::002160488671:role/GitHubTerraformRole
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./securitygroup

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./securitygroup

      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./securitygroup/tfplan

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download tfplan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./securitygroup

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::002160488671:role/GitHubTerraformRole
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Apply
        run: terraform apply -auto-approve ./securitygroup/tfplan
        working-directory: ./securitygroup