on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: 'Environment to deploy (e.g., development, staging, production)'
        required: true
      REGION:
        description: 'AWS Region to deploy (e.g., us-east-1, us-west-2)'
        required: true
      LAYERS:
        description: 'Comma-separated list of layers to deploy (e.g., ec2, securitygroup)'
        required: true
      APPROVE:
        description: 'Auto approve Terraform apply step (true/false)'
        required: false

permissions:
  id-token: write
  contents: read
  actions: read
  deployments: read

env:
  TFC_TOKEN: ${{ secrets.TFC_TOKEN }}  # set environment variable at workflow level

jobs:
  securitygroup:
    if: contains(inputs.LAYERS, 'securitygroup')  # condition to run this job only if 'securitygroup' is in the LAYERS input
    name: securitygroup
    runs-on: ubuntu-latest
    env:
      env_environment: ${{ inputs.ENVIRONMENT }}
      env_region: ${{ inputs.REGION }}
      env_layers: ${{ inputs.LAYERS }}
      password: ${{ secrets.DEV }}
    run: |
      echo "Environmental variable Environment: $env_environment"
      echo "Environmental variable Region: $env_region"
      echo "Environmental variable Layers: $env_layers"
      echo "Secret Password: $password"
      echo "tfc token is $TFC_TOKEN"

      if [[ "$env_layers" == *"securitygroup"* ]]; then
        echo "Starting deployment for securitygroup layer..."
        echo "Secrect value is ${{ secrets.DEV }} "
        echo "os.getenv('DEV')"