name: Release
run-name: Release - ${{ github.ref_name }} - ${{ inputs.ENVIRONMENT }} - ${{ inputs.REGION }}   # this will show in the github actions UI

on:
  workflow_dispatch:   # manual trigger
    inputs:            # input parameters for the workflow_dispatch event
      ENVIRONMENT:      # input parameter name
        description: 'Environment to deploy to' # description of the input parameter
        required: true  # make the input parameter required
        type: choice
        options:        # options for the choice input parameter
          - development
          - staging
          - production
        default: development # default value for the input parameter
      REGION:
        description: 'AWS Region to deploy to'
        required: true
        type: choice
        options:
          - us-east-1
          - eu-west-1
          - ap-southeast-1
        default: eu-west-1
      LAYERS:
        description: 'Layers to deploy'
        required: true
        type: choice
        options:
          - securitygroup
          - vpc
          - subnet
          - ec2
          - elb
          - database
          - application
        default: securitygroup
      APPROVE:
        description: 'Approve the deployment' # description of the input parameter
        required: true  # make the input parameter required 
        type: boolean  # boolean input parameter
        default: false # default value for the input parameter

permissions:
  id-token: write
  contents: read
  actions: read
  deployments: read

jobs:  # Correctly placed jobs block
  build-securitygroup:
    uses: ./.github/workflows/release_securitygroup.yml
    if: ${{ inputs.LAYERS == 'securitygroup' }}      # use inputs for workflow_dispatch event
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      REGION: ${{ inputs.REGION }}
      LAYERS: ${{ inputs.LAYERS }}
      APPROVE: ${{ inputs.APPROVE }}
    secrets: inherit              # inherit secrets from the current repository to reusable workflow

  # build-vpc:
  #   uses: ./.github/workflows/release_vpc.yml
  #   if: contains(inputs.LAYERS, 'vpc')        
  #   with:
  #     ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  #     REGION: ${{ inputs.REGION }}
  #     LAYERS: ${{ inputs.LAYERS }}
  #     APPROVE: ${{ inputs.APPROVE }}
  #   secrets: inherit              # inherit secrets from the current repository to reusable workflow
    
  # build-subnet:
  #   uses: ./.github/workflows/release_subnet.yml
  #   if: contains(inputs.LAYERS, 'subnet')
  #   with:
  #     ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  #     REGION: ${{ inputs.REGION }}
  #     LAYERS: ${{ inputs.LAYERS }}
  #     APPROVE: ${{ inputs.APPROVE }}
  #   secrets: inherit              # inherit secrets from the current repository to reusable workflow

  # build-ec2:
  #   uses: ./.github/workflows/release_ec2.yml 
  #   if: contains(inputs.LAYERS, 'ec2')
  #   with:
  #     ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  #     REGION: ${{ inputs.REGION }}
  #     LAYERS: ${{ inputs.LAYERS }}
  #     APPROVE: ${{ inputs.APPROVE }}
  #   secrets: inherit              # inherit secrets from the current repository to reusable workflow
